# Generated by Django 4.2.11 on 2024-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=100000)),
                ("adm_no", models.IntegerField(max_length=6)),
                ("class_sec", models.CharField(max_length=1000)),
                ("parent", models.CharField(max_length=1000)),
            ],
        ),
    ]
