# Generated by Django 5.0.3 on 2024-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="adm_no",
            field=models.CharField(max_length=6),
        ),
    ]
