# Generated by Django 5.0.3 on 2024-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seats", "0003_slot_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot_1",
            name="seat_2",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
