# Generated by Django 4.2.11 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seats", "0004_alter_slot_1_seat_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_1", models.CharField(max_length=2)),
                ("seat_2", models.CharField(blank=True, max_length=2, null=True)),
                ("adm_no", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Slot_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_1", models.CharField(max_length=2)),
                ("seat_2", models.CharField(blank=True, max_length=2, null=True)),
                ("adm_no", models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="slot",
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
